global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Si vous ajoutez un exporter (ex. nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']

  - job_name: 'angular'
    static_configs:
      - targets: ['localhost:4200']
    metrics_path: '/metrics'
