name: CI/CD for Static Web App

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Récupérer le code
      - uses: actions/checkout@v3
        with:
          submodules: true

      # 2) Installer Node & cache NPM
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3) Installer les dépendances
      - name: npm install
        run: npm ci

      # 4) Linter
      - name: npm run lint
        run: npm run lint

      # 5) Tests unitaires
      - name: npm test
        run: npm test

      # 6) E2E tests (facultatif)
      - name: npm run e2e
        run: npm run e2e

      # 7) Build pour la prod
      - name: npm run build
        run: npm run build

      # 8) Déployer sur Azure Static Web Apps
      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Le secret que vous avez déjà dans GitHub : AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FLOWER_07EC71B03
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FLOWER_07EC71B03 }}
          repo_token:                              ${{ secrets.GITHUB_TOKEN }}   # pour laisser l’action créer des commentaires si besoin
          action: "upload"
          app_location: "/"                      # chemin racine de votre site
          api_location: ""                       # pas d’Azure Functions
          output_location: "dist/angular-basic"  # votre dossier de build
